defmodule ReplicantServer.Accounts do
  @moduledoc """
  The Accounts context for user management.

  Identity is a server-minted surrogate id (random UUID, assigned once).
  Email is a mutable, unique attribute used to resolve accounts on first
  contact; it is never used to derive the id.
  """

  import Ecto.Query
  alias ReplicantServer.Repo
  alias ReplicantServer.Accounts.User
  alias ReplicantServer.Auth

  @doc """
  Gets the user for `email`, creating one (with an autogenerated id) if none
  exists. Safe under concurrent first contact: an insert lost to the email
  unique constraint falls back to re-reading the winner's row.
  """
  def get_or_create_user(email) do
    normalized = Auth.normalize_email(email)

    case get_user_by_email(normalized) do
      nil -> create_or_reread(normalized)
      user -> {:ok, user}
    end
  end

  defp create_or_reread(normalized) do
    case create_user(normalized) do
      {:ok, user} ->
        {:ok, user}

      {:error, %Ecto.Changeset{} = changeset} ->
        if email_taken?(changeset) do
          case get_user_by_email(normalized) do
            nil -> {:error, :user_resolution_failed}
            user -> {:ok, user}
          end
        else
          {:error, changeset}
        end
    end
  end

  defp email_taken?(%Ecto.Changeset{errors: errors}) do
    Enum.any?(errors, fn
      {:email, {_msg, opts}} -> opts[:constraint] == :unique
      _ -> false
    end)
  end

  @doc """
  Gets (by email) or creates the user and sets `display_name`. Idempotent:
  repeat calls update the display name in place. Used to mint factory
  contributors ahead of the backfill.
  """
  def upsert_user(email, display_name) do
    normalized = Auth.normalize_email(email)

    case get_user_by_email(normalized) do
      nil ->
        %User{}
        |> User.changeset(%{email: normalized, display_name: display_name})
        |> Repo.insert()

      %User{} = user ->
        user
        |> User.changeset(%{display_name: display_name})
        |> Repo.update()
    end
  end

  @doc """
  The user's presentable name: `display_name` when set, otherwise the local
  part of their email.
  """
  def display_name(%User{display_name: name}) when is_binary(name) and name != "", do: name
  def display_name(%User{email: email}), do: email |> String.split("@") |> hd()

  @doc """
  Gets a user by ID.
  """
  def get_user(id) do
    Repo.get(User, id)
  end

  @doc """
  Gets a user by email.
  """
  def get_user_by_email(email) do
    normalized = Auth.normalize_email(email)
    Repo.one(from u in User, where: u.email == ^normalized)
  end

  @doc """
  Creates a user with the given email; the id is autogenerated.
  """
  def create_user(email) do
    %User{}
    |> User.changeset(%{email: email})
    |> Repo.insert()
  end

  @doc """
  Changes a user's email. The id — and therefore all document ownership —
  is unaffected.
  """
  def update_user_email(%User{} = user, new_email) do
    user
    |> User.changeset(%{email: Auth.normalize_email(new_email)})
    |> Repo.update()
  end

  @doc """
  Updates a user's last_seen_at timestamp.
  """
  def touch_last_seen(user) do
    user
    |> Ecto.Changeset.change(last_seen_at: DateTime.utc_now())
    |> Repo.update()
  end
end
